--- 
abstract: ~
author: Jonathan Rockway C<< jrockway AT cpan.org >>.
build_requires: 
  Catalyst: 5.7001
  Path::Class: 0
  Storable: 0
  Test::MockObject: 0
  Test::More: 0
  Test::WWW::Mechanize::Catalyst: 0
  ok: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-View-Templated
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Component::ACCEPT_CONTEXT: 0.03
  Class::C3: 0
  Path::Class: 0
version: 0.02
